# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
