# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20161221_0328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogmodel',
            table=None,
        ),
    ]
