# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
