# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='repassword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
