# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170104_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
